name: Build

on:
  workflow_run:
    workflows: ["Norminette check"]
    types:
      - completed
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make

      - name: Build main program
        run: make

      - name: Check if binary exists
        run: |
          if [ -f ./minishell ]; then
            echo "Binary compiled successfully"
            ls -la ./minishell
          else
            echo "Binary not found"
            exit 1
          fi
