name: CI

on:
  push:
  pull_request:

jobs:
  Norminette:
    uses: ./.github/workflows/norminette.yml

  Build:
    needs: Norminette
    uses: ./.github/workflows/build.yml

  Test:
    needs: Build
    uses: ./.github/workflows/test.yml
