name: Norminette

on:
  workflow_call:

jobs:
  Norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Create virtual environment
        run: uv venv

      - name: Install and run norminette
        run: |
          source .venv/bin/activate
          uv pip install norminette
          norminette src/ include/ lib/
